In [1]:
!pip install nltk==3.9.1


[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
paragraph =  """I have three visions for India. In 3000 years of our history, people from all over 
               the world have come and invaded us, captured our lands, conquered our minds. 
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours. 
               Yet we have not done this to any other nation. We have not conquered anyone. 
               We have not grabbed their land, their culture, 
               their history and tried to enforce our way of life on them. 
               Why? Because we respect the freedom of others.That is why my 
               first vision is that of freedom. I believe that India got its first vision of 
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India 
               stands up to the world, no one will respect us. Only strength respects strength. We must be 
               strong not only as a military power but also as an economic power. Both must go hand-in-hand. 
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of 
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life. 
               I see four milestones in my career"""

In [10]:
import nltk
import re # re libray will use for regular expression 
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [11]:
ps = PorterStemmer()
wordnet= WordNetLemmatizer() 
sentences = nltk.sent_tokenize(paragraph) 

corpus = [] 

# Create the empty list name as corpus becuase after cleaned the data corpus will store this clean data

In [13]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\acer\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\acer\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\acer\AppData\Roaming\nltk_data...
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\acer\AppData\Roaming\nltk_data...


True

In [20]:
print("=" * 60)
print("TEXT PREPROCESSING RESULTS")
print("=" * 60)
# Process sentences
for i in range(len(sentences)):
    review = re.sub('[^a-zA-Z]', ' ', sentences[i]) 
    review = review.lower() 
    review = review.split()
    review = [wordnet.lemmatize(word) for word in review if word not in set(stopwords.words('english'))]   
    review = ' '.join(review)
    corpus.append(review)

print(f"\n📊 Total sentences found: {len(sentences)}")
print(f"📊 Total cleaned sentences: {len(corpus)}")
print(f"📊 First 3 sentences:\n")

TEXT PREPROCESSING RESULTS

📊 Total sentences found: 31
📊 Total cleaned sentences: 93
📊 First 3 sentences:



In [14]:
for i in range(len(sentences)):
    review = re.sub('[^a-zA-Z]', ' ', sentences[i]) 
    review = review.lower() 
    review = review.split()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = [wordnet.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]   
    review = ' '.join(review)
    corpus.append(review) 

In [15]:
#bag of words
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X_bow = cv.fit_transform(corpus).toarray()

In [21]:
print(f"\n📊 BAG OF WORDS MODEL:")
print(f"Matrix shape: {X_bow.shape} (sentences × vocabulary)")
print(f"Vocabulary size: {len(cv.vocabulary_)} words")
print(f"First 10 vocabulary words: {list(cv.vocabulary_.keys())[:10]}")
print(f"Bag of Words matrix (first 5 sentences, first 10 features):")
print(X_bow[:5, :10])


📊 BAG OF WORDS MODEL:
Matrix shape: (31, 111) (sentences × vocabulary)
Vocabulary size: 111 words
First 10 vocabulary words: ['three', 'vision', 'india', 'year', 'histori', 'peopl', 'world', 'come', 'invad', 'captur']
Bag of Words matrix (first 5 sentences, first 10 features):
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]]


In [16]:
#document matrix
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer()
X_tf = tf.fit_transform(corpus).toarray()

In [22]:
print(f"\n📊 TF-IDF MODEL:")
print(f"Matrix shape: {X_tf.shape} (sentences × vocabulary)")
print(f"Vocabulary size: {len(tf.vocabulary_)} words")
print(f"TF-IDF matrix (first 5 sentences, first 10 features):")
print(X_tf[:5, :10])


📊 TF-IDF MODEL:
Matrix shape: (31, 111) (sentences × vocabulary)
Vocabulary size: 111 words
TF-IDF matrix (first 5 sentences, first 10 features):
[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.28867513 0.         0.         0.         0.
  0.         0.         0.         0.28867513]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.74606136 0.
  0.         0.         0.         0.        ]]


In [23]:
print(f"\n📊 FEATURE NAMES (first 10):")
feature_names = cv.get_feature_names_out()
print(list(feature_names[:10]))


📊 FEATURE NAMES (first 10):
['achiev', 'alexand', 'also', 'among', 'anyon', 'area', 'assur', 'believ', 'brahm', 'british']


In [24]:
print(f"\n📊 SUMMARY STATISTICS:")
print(f"Total sentences: {len(sentences)}")
print(f"Vocabulary size (BoW): {len(cv.vocabulary_)}")
print(f"Vocabulary size (TF-IDF): {len(tf.vocabulary_)}")
print(f"Sparsity in BoW: {(X_bow == 0).sum() / X_bow.size * 100:.2f}% zeros")
print(f"Sparsity in TF-IDF: {(X_tf == 0).sum() / X_tf.size * 100:.2f}% zeros")


📊 SUMMARY STATISTICS:
Total sentences: 31
Vocabulary size (BoW): 111
Vocabulary size (TF-IDF): 111
Sparsity in BoW: 95.52% zeros
Sparsity in TF-IDF: 95.52% zeros


In [ ]:
#assignment 1-create manual embeddings for words
embeddings = {
"AI":[0.1,0.2,0.3],
"NLP":[0.4,0.5,0.6]
}
print(embeddings["AI"])
print(embeddings["NLP"])

[0.1, 0.2, 0.3]
[0.4, 0.5, 0.6]


In [26]:
#assignment 2- convert token IDs into embeddings
import numpy as np
embedding_matrix = np.array([
[0.1,0.2,0.3],
[0.4,0.5,0.6],
[0.7,0.8,0.9]
])
token_ids = [0,2,1]
embeddings = embedding_matrix[token_ids]
print(embeddings)

[[0.1 0.2 0.3]
 [0.7 0.8 0.9]
 [0.4 0.5 0.6]]
